logging:
  level:
    org.springframework.security: TRACE

spring:
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath*:db/schema.sql
  thymeleaf:
    cache: false

server:
  servlet:
    session:
      persistent: true